### ISSUE TITLE
required JDK version (17) not specified in README

### ISSUE THREAD

**Issue by elroykanye** [transkript/ireportcard-client#20]
`Hm. Java 17 was used. Features such as records and switch returns are used in the backend that's why we have this requirement. Just do the necessary updates. We may have to include this in the readme, don't you think?`

_Originally posted by @elroykanye in https://github.com/transkript/reportcard-frontend/issues/10#issuecomment-1158592154_

It should be relatively simple to state which JDK version is required to launch the backend. This is to avoid compatibility issues with some features occuring only in versions above and including Java 14 and 17.

**Comment by mofirojean** [comment]
hi @elroykanye , can i work on this issue
