### ISSUE TITLE
[BUG] Academic year duplicates

### ISSUE THREAD

**Issue by Dezzy12** [transkript/ireportcard-client#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

There is a duplicate in the Academic year section.
That is a school year can be inputted twice

This is a screenshot of the issue
![Screenshot from 2022-06-22 11-31-00](https://user-images.githubusercontent.com/98283956/175009346-9f976fba-c2d2-44cc-8ac8-564c61cd4908.png)

### Expected Behavior

When i add an academic year that already exist, it is to display an error 

### Steps To Reproduce

1. In settings
2. Academic years
3. Added a year twice

### Environment

```markdown
- OS:Ubuntu 20.04
- Node: 16.15.1
- npm: 8.11.0
```

### Anything else?

No

**Comment by elroykanye** [comment]
I think this will involve the backend instead
