### ISSUE TITLE
Centralized response message handling on error and on creation

### ISSUE THREAD

**Issue by elroykanye** [transkript/ireportcard-client#29]
### Description

Currently, there are a lot of parts in the codebase which contain an addition to the `MessageService` of a response message.
An example of such is this: 
```typescript
this.gradeService.save(grade).subscribe({
     next: (res) => {
          addToMessageService(this.msg, 'success', 'Add grade successfully', res.message)
          this.loadGrades();
     },
     error: (err) => addToMessageService(this.msg, 'error', 'Add grade failed', err.message)
});
```

As shown, the message in the response body in the successful part of this observable is added to the `messageService`, as well as the error. Recently an [http response interceptor](https://github.com/transkript/reportcard-frontend/blob/master/src/app/interceptors/http-response.interceptor.ts) was implemented to take care of this for all responses, making this `addToMessageService()` unnecessary in most components. 

My issue then is that, two messages are toasted in some events where it should be just one. So removing this addition to the messageService should be removed in most of the components implemented this way. This may solve the problem stated at #19 , since these response messages come from the backend and should then make a lot of sense.

**Comment by mulfranck** [comment]
Indeed, it throughs some light on the codebase. 
So if I get you right, the thing here is to identify the components that needs just a successful message and remove the error block and vice versa.

**Comment by mulfranck** [comment]
Please I have some confusion regarding this task, what about the functions that are involved within the `next:` code block?
In the extract above, I am talking about   `this.loadGrades();`

**Comment by mulfranck** [comment]
I was going through this but release, I never understood something.
With the above extract, when the `addToMessageService()` methods are removed should is the `loadGrade()` directly called in `next:` and the `error:` completely removed? like so

```js
this.gradeService.save(grade).subscribe({
     next: (res) => { this.loadGrades(); },
     error: (err) => {}
});
``` 
or like so
```js
this.gradeService.save(grade).subscribe({
     next: (res) => { this.loadGrades(); }
});
```

or how can the task be done? _a little confusing_😕

**Comment by elroykanye** [comment]
Actually, both are the same thing and fall along the lines of what we are trying to accomplish.
I would go for the option without the `err` property as it is not necessary since its body will be empty. What do you think?

**Comment by mulfranck** [comment]
Yes, If there is nothing it does it's better removed.

**Comment by elroykanye** [comment]
Updates on this?
