### ISSUE TITLE
[Feature Request] Landing page required

### ISSUE THREAD

**Issue by de-lia** [transkript/ireportcard-client#33]
### Is your feature request related to a problem?

Yes, it is

### Please describe the problem this request is related to. If you didn't mark the checkbox above, please skip this question.

Upon opening the localhost:4200/ as described by the readme of this repository, all I can see is a blank page consisting of a 'header' and a long red line of 'Hello World' which is unresponsive and insensitive.
![Screenshot from 2022-08-01 12-36-45](https://user-images.githubusercontent.com/94251956/182148883-e645f3d8-fd97-4343-a4b1-5091ddef31e0.png)

### Please describe solution to you'd like to see.

In my opinion, I think it should be replaced by a landing page that welcomes newbies into the system with a signup/login form and other details about the report-card system (for example, a navigation bar which includes About, Help, Contact, etc).

### Please describe the benefit of your feature.

The page will be used to encourage visitors to the reportcard system to take action (by either signing up or getting a free trial, for example). The landing page will help in providing information about the item(in this case, the reportcard system).

### Please describe the alternatives you have considered.

I do not think there are any alternatives to a landing page for this system since the landing page is basically one of the most used web tools to attract a visitor's attention.

**Comment by elroykanye** [comment]
I agree with your ideas for this landing page. I think we can have an arrangement for further details that should be included on this, don't you think?

**Comment by de-lia** [comment]
Sounds great. Would like to be part of this.

**Comment by elroykanye** [comment]
Hi @de-lia , I have assigned this issue to you. Keep in mind that we are primarily migrating from bootstrap to [PrimeFlex](https://www.primefaces.org/primeflex/) .

**Comment by de-lia** [comment]
> Hi @de-lia , I have assigned this issue to you. Keep in mind that we are migrating from bootstrap to primarily [PrimeFlex](https://www.primefaces.org/primeflex/) .

Okay

**Comment by de-lia** [comment]
Facing some challenges with finding the file which I would be working on for the landing page.
@elroykanye could I please get some help?

**Comment by elroykanye** [comment]
You may find that here: https://github.com/transkript/reportcard-frontend/tree/master/src/app/components/rc-welcome

**Comment by de-lia** [comment]
Thanks!
