### ISSUE TITLE
[BUG] flash of the un-styled content before the styling is applied

### ISSUE THREAD

**Issue by mulfranck** [transkript/ireportcard-client#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On the homepage, if you reload  the page there is a flash of the un-styled content before the styling is applied

### Expected Behavior

- Just have the page reload without any flash.

### Steps To Reproduce

1. On the homepage, click on the refresh icon of the browser or `Cntrl+R`

### Environment

```markdown
- OS: Ubuntu 22.04
- Browser: Firefox, 104.0.1
```

**Comment by elroykanye** [comment]
This happens because CSS is still being fetched. I think this should be in the same light as #65
