### ISSUE TITLE
[BUG] Cannot update/change password

### ISSUE THREAD

**Issue by mulfranck** [transkript/ireportcard-client#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am login, having the old password, when I input a new password on trying to save it I have a popup message saying I am not a user while the I am still logged in.

### Expected Behavior

- Expected an update of password

### Steps To Reproduce

1. Login as a student, and scroll down
2. Input the Old password and a new password
3. Click on save

### Environment

```markdown
- OS:Ubuntu 22.04
- Browser: Firefox 104.0.1
```

**Comment by elroykanye** [comment]
Hello, recent changes to the backend resolved this issue. Thanks very much @mulfranck
