### ISSUE TITLE
No displayed content

### ISSUE THREAD

**Issue by mulfranck** [transkript/ireportcard-client#7]
After countless errors trying to execute `ng serve`, I decided to execute `npm start` from the _package.json_ file.

After development the browser displayed no content
![empty](https://user-images.githubusercontent.com/74215941/169685603-9802d811-48ab-4458-90f0-1b57a4b33ef6.png)

I am using WSL1 ubuntu 20.04 installed, and Chrome browser.

**Comment by elroykanye** [comment]
Hi @mulfranck , go to this link `localhost:8090/dashboard/home`

Thanks for your contribution! :)

**Comment by elroykanye** [comment]
This issue exists because we haven't built the component which should be display at this level. That will be done as soon as possible and then we can close. I will be working on this soon.

**Comment by elroykanye** [comment]
Oh yes that's right. I confused that of the backend with that of the frontend.
Thanks.

**Comment by elroykanye** [comment]
Hello @mulfranck ! Checkout the work done at #46
