### ISSUE TITLE
username instead of email

### ISSUE THREAD

**Issue by mofirojean** [transkript/ireportcard-client#71]
### Description

In the sign in field the email field be username and not email 
since in the cause of signing up there is no field requesting for an email

an image of this issue can be seen below
![Screenshot from 2022-09-03 12-13-33](https://user-images.githubusercontent.com/93985482/188267973-29e490ec-2f57-485d-83f9-d5e31622f139.png)

**Comment by mofirojean** [comment]
hey @elroykanye can i solve this issue

**Comment by elroykanye** [comment]
By all means, please go ahead
