### ISSUE TITLE
Improve error message if signup email exists already.

### ISSUE THREAD

**Issue by moforemmanuel** [transkript/ireportcard-client#72]
### Description

**"This action is causing a conflict on the database"** is too vague for the expected UX, specially for "not-so-techie" users

![Screenshot from 2022-09-03 15-01-04](https://user-images.githubusercontent.com/77344844/188273895-dc372365-6254-471d-8807-7a14c442786c.png)

**Comment by Dezzy12** [comment]
Hello, could i work on this?

**Comment by elroykanye** [comment]
Yes please
