### ISSUE TITLE
Applications section not functioning

### ISSUE THREAD

**Issue by Dezzy12** [transkript/ireportcard-client#75]
### Description

In the applications section the "Apply" button does not respond.
![Screenshot_20221023-155626_Chrome](https://user-images.githubusercontent.com/98283956/197399552-b139ab5a-8dd5-4863-93d2-bafbc2b3de92.jpg)

**Comment by elroykanye** [comment]
I think that whole section should be removed. It is not necessary as this is automatically requested during login.

**Comment by Dezzy12** [comment]
Okay
