### ISSUE TITLE
class levels not stated

### ISSUE THREAD

**Issue by mofirojean** [transkript/ireportcard-client#78]
### Description

Each time i refresh the site i receive a pop up telling me to select a class level of which none is stated

here is a picture of the issue
![Screenshot from 2022-10-23 16-54-58](https://user-images.githubusercontent.com/93985482/197402473-4af6ffb8-3535-465e-a2ab-e043a4927812.png)

**Comment by elroykanye** [comment]
This is not an issue, as the class levels need to be created by the admin before they are created. I think we should close this as it poses no problem with the code.
